#!/bin/bash

# JupyterLab extensions
# ---------------------

# interactive Matplotlib plots 
# ... see https://github.com/matplotlib/ipympl#install-the-jupyterlab-extension
jupyter labextension install @jupyter-widgets/jupyterlab-manager

# Make it possible to store after the Binder stopped.
jupyter labextension install jupyter-offlinenotebook

# HDF5 support to read line cache files and rovibrational energy files
jupyter labextension install @jupyterlab/hdf5

# JupyterLab renderer support
jupyter labextension install jupyterlab-plotly@4.14.1 plotlywidget@4.14.1


jupyter lab build --name="RadisLab"


# Datasets
# --------

# Create folders if needed
cd ~
mkdir databases
cd databases
mkdir HITEMP

# Download HITEMP 
cd ~/databases/HITEMP
# ... CO
wget https://hitran.org/hitemp/data/bzip2format/05_HITEMP2019.par.bz2

# ... CO2
mkdir CO2 
cd CO2
wget wget -np -nH --cut-dirs=6 -r https://hitran.org/hitemp/data/HITEMP-2010/CO2_line_list/
rm index*

# Unzip HITEMP
cd ~/databases/HITEMP
# ... CO
python hitemp_bz2_extract.py 05_HITEMP2019.par.bz2
rm 05_HITEMP2019.par.bz2

# ... CO2
cd CO2 
unzip '*.zip'
rm *.zip


# Initial runs
# ------------
# (to auto-download / cache some database files
# see https://github.com/radis/radis-lab/issues/9

# Init databases
cd ~/databases
python init_radis_config.py

cd ~
papermill welcome.ipynb /dev/null 
cd examples
papermill compare_CO_HITRAN_HITEMP.ipynb /dev/null 
cd ~/examples/co2-4080-4500nm
papermill co2-4080-4500.ipynb /dev/null 


# Cache all line databases 
# ... trying to load all CO2 at once. May have problem if 2 GB RAM? 
cd ~/databases
python cache_line_databases.py