#!/bin/bash

# See https://mybinder.readthedocs.io/en/latest/using/config_files.html

# set environment variables
# ...

# execute run commands
# ...

# Init RADIS config
python ~/databases/init_radis_config.py




# Workspace Layout 

# ... Import the workspace layout into JupyterLab (windows opened, etc.)
jupyter lab workspaces import binder/workspace.json

exec "$@"